GRANT ALL PRIVILEGES ON *.* FROM 'root'@'localhost'; 
//REVOKE GRANT OPTION ON *.* FROM 'root'@'localhost'; 
//GRANT USAGE ON *.* TO 'root'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
